# Generated by Django 2.2 on 2019-04-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Rbl name')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='Rbl address')),
                ('link', models.CharField(max_length=200, null=True, verbose_name='Rbl link')),
            ],
        ),
    ]
