# Generated by Django 3.0.4 on 2020-04-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('ipaddress', models.GenericIPAddressField(unique=True, verbose_name='Ip address')),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Rbl name')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='Rbl address')),
                ('link', models.CharField(max_length=200, null=True, verbose_name='Rbl link')),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
