# Generated by Django 3.2.7 on 2021-10-05 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('ipaddress', models.GenericIPAddressField(unique=True, verbose_name='Ip address')),
                ('updated', models.DateTimeField(editable=False)),
                ('created', models.DateTimeField(editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Rbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Rbl name')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='Rbl address')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rbl link')),
                ('updated', models.DateTimeField(editable=False)),
                ('created', models.DateTimeField(editable=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RblRcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Rbl Return Code')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rbl Return Code text')),
                ('rbl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coredata.rbl')),
            ],
        ),
        migrations.CreateModel(
            name='IpRblHistoric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed', models.BooleanField(default=False)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(editable=False)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coredata.ip')),
                ('rblrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coredata.rblrcode')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
